# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0-14-gb6fae18
_src_path: https://github.com/cetmix/cetmix-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: 'ahmetzianovvadim

    '
org_slug: 'ahmetzianovadim

    '
rebel_module_groups: []
repo_description: some description
repo_name: final-repo
repo_slug: final-repo
repo_website: https://cetmix.com
travis_apt_packages: []
travis_apt_sources: []

